## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np
x = [[1, 2], [3, 4]]
y = [[5, 6], [7, 8]]
z = np.dot(x, y)
print(z)


[[19 22]
 [43 50]]


## Write a NumPy program to compute the determinant of a given square array

In [5]:
import numpy as np
from numpy import linalg as LA
a = np.array([[6, 2], [1, 4]])
print(np.linalg.det(a))


22.000000000000004


## Write a NumPy program to compute the cross product of two given vectors

In [6]:
import numpy as np
x = [[1, 2], [3, 4]]
y = [[5, 6], [7, 8]]
z = np.cross(x, y)
print(z)

[-4 -4]


## Write a NumPy program to compute the condition number of a given matrix

In [8]:
import numpy as np
x = np.array([[1,2],[3,4]])
z =  np.linalg.cond(x)
print(z)


14.933034373659265


## Write a NumPy program to compute the inverse of a given matrix

In [11]:

import numpy as np
x = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(np.linalg.inv(x))


[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
